/**
 * Curated VSCode theme catalog. Generated by `bun run themes:sync` from
 * `tm-themes` + hand-authored entries in `src/themes/assets/`.
 *
 * Do not edit by hand. To change the catalog, edit `frontend/scripts/sync-themes.ts`
 * and re-run `bun run themes:sync`.
 */

import type { RawThemeJson } from "../../lib/theme/types";

export interface ThemeCatalogEntry {
  /** Stable id used in config and dynamic-import paths. */
  id: string;
  /** Display label in the picker. */
  label: string;
  /** "dark" | "light" — drives `data-kb-theme` toggling and picker grouping. */
  type: "dark" | "light";
  /** Lazy-load the raw VSCode JSON for this theme. */
  load: () => Promise<RawThemeJson>;
  /** Provenance string, e.g. "tm-themes@1.12.2" or "local". */
  sourceVersion: string;
}

export const THEME_CATALOG: readonly ThemeCatalogEntry[] = [
  {
    id: "raum-default-dark",
    label: "Default",
    type: "dark",
    load: () => import("./raum-default-dark.json").then((m) => m.default as RawThemeJson),
    sourceVersion: "local",
  },
  {
    id: "dracula",
    label: "Dracula",
    type: "dark",
    load: () => import("./dracula.json").then((m) => m.default as RawThemeJson),
    sourceVersion: "tm-themes@1.12.2",
  },
  {
    id: "one-dark-pro",
    label: "One Dark Pro",
    type: "dark",
    load: () => import("./one-dark-pro.json").then((m) => m.default as RawThemeJson),
    sourceVersion: "tm-themes@1.12.2",
  },
  {
    id: "tokyo-night",
    label: "Tokyo Night",
    type: "dark",
    load: () => import("./tokyo-night.json").then((m) => m.default as RawThemeJson),
    sourceVersion: "tm-themes@1.12.2",
  },
  {
    id: "catppuccin-mocha",
    label: "Catppuccin Mocha",
    type: "dark",
    load: () => import("./catppuccin-mocha.json").then((m) => m.default as RawThemeJson),
    sourceVersion: "tm-themes@1.12.2",
  },
  {
    id: "rose-pine",
    label: "Rosé Pine",
    type: "dark",
    load: () => import("./rose-pine.json").then((m) => m.default as RawThemeJson),
    sourceVersion: "tm-themes@1.12.2",
  },
  {
    id: "nord",
    label: "Nord",
    type: "dark",
    load: () => import("./nord.json").then((m) => m.default as RawThemeJson),
    sourceVersion: "tm-themes@1.12.2",
  },
  {
    id: "github-dark",
    label: "GitHub Dark",
    type: "dark",
    load: () => import("./github-dark.json").then((m) => m.default as RawThemeJson),
    sourceVersion: "tm-themes@1.12.2",
  },
  {
    id: "solarized-dark",
    label: "Solarized Dark",
    type: "dark",
    load: () => import("./solarized-dark.json").then((m) => m.default as RawThemeJson),
    sourceVersion: "tm-themes@1.12.2",
  },
  {
    id: "monokai",
    label: "Monokai",
    type: "dark",
    load: () => import("./monokai.json").then((m) => m.default as RawThemeJson),
    sourceVersion: "tm-themes@1.12.2",
  },
  {
    id: "github-light",
    label: "GitHub Light",
    type: "light",
    load: () => import("./github-light.json").then((m) => m.default as RawThemeJson),
    sourceVersion: "tm-themes@1.12.2",
  },
  {
    id: "solarized-light",
    label: "Solarized Light",
    type: "light",
    load: () => import("./solarized-light.json").then((m) => m.default as RawThemeJson),
    sourceVersion: "tm-themes@1.12.2",
  },
  {
    id: "catppuccin-latte",
    label: "Catppuccin Latte",
    type: "light",
    load: () => import("./catppuccin-latte.json").then((m) => m.default as RawThemeJson),
    sourceVersion: "tm-themes@1.12.2",
  },
];

export const DEFAULT_THEME_ID = "raum-default-dark";
